export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORBIDDEN: '/403',
  USERS: '/users',
  PARTICIPANTS: '/participants',
  CATEGORIES: '/categories',
  EVENTS: '/events',
  MY_REGISTRATIONS: '/my-registrations',
  EVENT_CREATE: '/events/new',
  EVENT_EDIT: '/events/:id/edit',
  EVENT_DETAIL: '/events/:id',
  EVENT_REGISTRATIONS: '/events/:eventId/registrations',
  EVENT_CHECK_IN: '/events/:eventId/check-in',
  CHANGE_PASSWORD: '/change-password',
} as const;
